service:

  - item:
    title: Associate Editor
    institute: Journal of Atmospheric and Oceanic Technology, American Meteorological Society
    location: USA
    date: Summer 2024 - Present
    description: Review and evaluate article submissions to the Journal of Atmospheric and Oceanic Technology, with focus on the ocean.

  - item:
    title: Judge and Reviewer
    institute: Junior Science and Humanities Symposium
    location: Fairbanks, Alaska, USA
    date: Spring 2021, Spring 2023, Spring 2024
    description: Reviewed students' reports and participated as a judge for the state JSHS competition. Guided students in their project work.
