# Site settings
title: Alaskan Researcher
author: Doug Keller
lang: en_US

email: dg.kllr.jr@gmail.com
twitter: ak_researcher
github: dkllrjr
gitlab: dkllrjr
itchio: socratic-salmon-games
twitch: alaskanresearcher
youtube: "UCWux0xszsp373cTWb-yBJwA"
linkedin: "dg-kllr-jr"

description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
