# Site settings
title: Alaskan Researcher
author: Doug Keller
lang: en_US

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: redcarpet
sass:
    indentWidth: 4
    style: compact
    precision: 10
plugins:
    - jekyll-sitemap
    - jekyll-seo-tag
exclude:
    - Gemfile
    - Gemfile.lock
    - vendor/**
    - archive/**

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
